### ISSUE TITLE
Module error 

### ISSUE THREAD

**Issue by raptor-boys** [Psi505/Routersploit-Installer#4]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/routersploit/rsf.py", line 10, in <module>                      from routersploit.interpreter import RoutersploitInterpreter
  File "/data/data/com.termux/files/home/routersploit/routersploit/interpreter.py", line 12, in <module>
    from future.builtins import input                                                                ModuleNotFoundError: No module named 'future'

**Comment by Psi505** [comment]
Can you please specify how you got this error?
